name: Update Panel Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Panel version to build'
        required: true
env:
  PANEL_PROJECT_NAME: pterodactyl-panel # Dockerhub project

jobs:
  build_push_panel:
    name: Build and Push Panel Container
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v2
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./manifest/images/panel
        file: ./manifest/images/panel/Dockerfile
        platforms: linux/amd64,linux/arm64
        build-args: VERSION=${{ github.event.inputs.version }}
        push: true
        tags: |
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PANEL_PROJECT_NAME }}:latest"
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PANEL_PROJECT_NAME }}:${{ github.event.inputs.version }}"
